name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install . pytest flake8
      - name: Lint
        run: flake8 src tests
      - name: Tests
        run: pytest -q

